#pragma once
#include <map>
#include <string>
#include <windows.h>

enum class StrId {
  Menu_File,
  Menu_NewSet,
  Menu_Exit,
  Menu_Run,
  Menu_RunSet,
  Menu_Preview,
  Menu_Verify,
  Menu_Log,
  Menu_LogHistory,
  Menu_Help,
  Menu_About,
  Menu_Set,
  Menu_Unit,
  Menu_Backup,

  Ctx_Run,
  Ctx_Preview,
  Ctx_EditUnit,
  Ctx_EditSet,
  Ctx_AddUnit,
  Ctx_Duplicate,
  Ctx_Delete,
  Ctx_Rename,
  Ctx_Refresh,
  Ctx_AddSet,

  Msg_ConfirmDeleteSet,
  Msg_ConfirmDeleteUnit,
  Msg_ConfirmExit,
  Msg_ConfirmTitle,
  Msg_SelectFirst,
  Msg_ProcessErrors,
  Msg_ProcessSuccess,
  Msg_StatusTitle,
  Main_Processing,

  Dlg_UnitName,
  Dlg_Source,
  Dlg_Target,
  Dlg_Browse,
  Dlg_MapNetwork,
  Dlg_Mode_Copy,
  Dlg_Mode_Sync,
  Dlg_Mode_Verify,
  Dlg_Mode_VerifyOnly,
  Dlg_Verification,
  Dlg_Verify_Full,
  Dlg_Verify_Criteria,
  Dlg_ErrorPolicy,
  Dlg_Policy_Cont,
  Dlg_Policy_Susp,
  Dlg_Engine,
  Dlg_Btn_Save,
  Dlg_SetName,
  Dlg_Description,
  Dlg_UnitsInSet,
  Dlg_Btn_Up,
  Dlg_Btn_Down,
  Dlg_SchedFrq,
  Dlg_Sched_Manual,
  Dlg_Sched_Daily,
  Dlg_Sched_Weekly,
  Dlg_Time_Title,
  Dlg_Day_Title,
  Dlg_Btn_SaveSet,

  Main_Stop,
  Main_MaxLog,
  Main_RestoreLayout,
  Main_SrcPath,
  Main_DstPath,
  Main_Error,
  Main_Info,
  Main_WorkerStop,
  Main_Ready,
  Main_WorkerIdle,
  Dlg_NewSet_Default,
  Dlg_NewSet_Desc_Default,
  Dlg_NewUnit_Default,

  Eng_Std,
  Eng_Par,
  Eng_Blk,
  Eng_Vss,
  Eng_Cmp,
  Err_SamePath,
  Err_AlreadyRunning,
  Ctx_SetAsSource,
  Ctx_SetAsTarget,
  Err_PathOverlap,

  Day_Sun,
  Day_Mon,
  Day_Tue,
  Day_Wed,
  Day_Thu,
  Day_Fri,
  Day_Sat,
  Dlg_History_Title,
  Dlg_History_Date,
  Dlg_History_Task,
  Dlg_History_Open
};

class Localization {
public:
  static std::map<StrId, std::wstring> s_strings;

  static void Init() {
    LANGID langId = GetUserDefaultUILanguage();
    WORD primaryLang = langId & 0xFF;

    // Detect language
    bool isJapanese = (primaryLang == LANG_JAPANESE);
    bool isSpanish = (primaryLang == LANG_SPANISH);
    bool isFrench = (primaryLang == LANG_FRENCH);
    bool isGerman = (primaryLang == LANG_GERMAN);

    if (isJapanese) {
      // Japanese (日本語)
      s_strings = {
          {StrId::Menu_File, L"ファイル"},
          {StrId::Menu_NewSet, L"新規バックアップセット"},
          {StrId::Menu_Exit, L"終了"},
          {StrId::Menu_Run, L"実行"},
          {StrId::Menu_RunSet, L"バックアップ実行"},
          {StrId::Menu_Preview, L"プレビュー (Dry Run)"},
          {StrId::Menu_Verify, L"整合性チェック (Verify)"},
          {StrId::Menu_Help, L"ヘルプ"},
          {StrId::Menu_About, L"SureBackupについて"},
          {StrId::Menu_Set, L"セット"},
          {StrId::Menu_Unit, L"ユニット"},
          {StrId::Menu_Backup, L"バックアップ"},
          {StrId::Menu_Log, L"ログ"},
          {StrId::Menu_LogHistory, L"実行履歴..."},

          {StrId::Ctx_Run, L"実行"},
          {StrId::Ctx_Preview, L"プレビュー"},
          {StrId::Ctx_EditUnit, L"バックアップユニット編集"},
          {StrId::Ctx_EditSet, L"バックアップセット編集"},
          {StrId::Ctx_AddUnit, L"ユニット追加"},
          {StrId::Ctx_Duplicate, L"複製"},
          {StrId::Ctx_Delete, L"削除"},
          {StrId::Ctx_Rename, L"名前の変更"},
          {StrId::Ctx_Refresh, L"更新"},
          {StrId::Ctx_SetAsSource, L"ソースに設定"},
          {StrId::Ctx_SetAsTarget, L"ターゲットに設定"},
          {StrId::Menu_Set, L"セット"},
          {StrId::Ctx_AddSet, L"セット追加"},

          {StrId::Dlg_UnitName, L"ユニット名:"},
          {StrId::Dlg_Source, L"ソースフォルダのパス:"},
          {StrId::Dlg_Target, L"ターゲットフォルダのパス:"},
          {StrId::Dlg_Browse, L"参照..."},
          {StrId::Dlg_MapNetwork, L"ネットワークドライブ接続..."},
          {StrId::Dlg_Mode_Copy, L"コピーモード (追記)"},
          {StrId::Dlg_Mode_Sync, L"同期モード (ミラー)"},
          {StrId::Dlg_Mode_Verify, L"整合性検証のみ"},
          {StrId::Dlg_Mode_VerifyOnly, L"整合性検証のみ"},
          {StrId::Dlg_Verification, L"検証方法:"},
          {StrId::Dlg_Verify_Full, L"バイト単位で検証 (完全)"},
          {StrId::Dlg_Verify_Criteria, L"サイズ/タイムスタンプのみ"},
          {StrId::Dlg_ErrorPolicy, L"エラー発生時のポリシー:"},
          {StrId::Dlg_Policy_Cont, L"継続 (ファイルをスキップ)"},
          {StrId::Dlg_Policy_Susp, L"一時停止 (ユニットを停止)"},
          {StrId::Dlg_Engine, L"処理エンジン:"},
          {StrId::Dlg_Btn_Save, L"保存"},
          {StrId::Dlg_SetName, L"バックアップセット名:"},
          {StrId::Dlg_Description, L"セットの説明:"},
          {StrId::Dlg_UnitsInSet, L"セット内のユニット:"},
          {StrId::Dlg_Btn_Up, L"上に移動"},
          {StrId::Dlg_Btn_Down, L"下に移動"},
          {StrId::Dlg_SchedFrq, L"スケジュール頻度:"},
          {StrId::Dlg_Sched_Manual, L"手動実行"},
          {StrId::Dlg_Sched_Daily, L"毎日実行"},
          {StrId::Dlg_Sched_Weekly, L"毎週実行"},
          {StrId::Dlg_Time_Title, L"実行時刻 (HH:MM):"},
          {StrId::Dlg_Day_Title, L"実行曜日 (毎週):"},
          {StrId::Dlg_Btn_SaveSet, L"セットを保存"},

          {StrId::Main_Stop, L"全てのタスクを停止"},
          {StrId::Main_MaxLog, L"ログを最大化"},
          {StrId::Main_RestoreLayout, L"レイアウト復元"},
          {StrId::Main_SrcPath, L"ソース: "},
          {StrId::Main_DstPath, L"ターゲット: "},
          {StrId::Main_Error, L"エラー"},
          {StrId::Main_Info, L"情報"},
          {StrId::Main_WorkerStop, L"停止"},
          {StrId::Main_Ready, L"準備完了"},
          {StrId::Main_WorkerIdle, L"アイドル"},
          {StrId::Dlg_NewSet_Default, L"新規バックアップセット"},
          {StrId::Dlg_NewSet_Desc_Default, L"バックアップのリスト"},
          {StrId::Dlg_NewUnit_Default, L"新規バックアップユニット"},

          {StrId::Eng_Std, L"標準エンジン (安定)"},
          {StrId::Eng_Par, L"マルチスレッド (高速)"},
          {StrId::Eng_Blk, L"ブロッククローン (差分同期)"},
          {StrId::Eng_Vss, L"VSS (スナップショット)"},
          {StrId::Eng_Cmp, L"比較エンジン (整合性チェック)"},
          {StrId::Err_SamePath,
           L"エラー: "
           L"ソースとターゲットに同じフォルダを指定することはできません。"},
          {StrId::Err_AlreadyRunning, L"バックアップは既に実行中です。"},
          {StrId::Err_PathOverlap,
           L"エラー: ソースとターゲットのパスが重複しています。"},
          {StrId::Ctx_SetAsSource, L"ソースとして設定"},
          {StrId::Ctx_SetAsTarget, L"ターゲットとして設定"},

          {StrId::Day_Sun, L"日曜日"},
          {StrId::Day_Mon, L"月曜日"},
          {StrId::Day_Tue, L"火曜日"},
          {StrId::Day_Wed, L"水曜日"},
          {StrId::Day_Thu, L"木曜日"},
          {StrId::Day_Fri, L"金曜日"},
          {StrId::Day_Sat, L"土曜日"},
          {StrId::Dlg_History_Title, L"実行履歴"},
          {StrId::Dlg_History_Date, L"実行日時"},
          {StrId::Dlg_History_Task, L"タスク名"},
          {StrId::Dlg_History_Open, L"ログを開く"},

          {StrId::Msg_ConfirmDeleteSet,
           L"このバックアップセットを削除してもよろしいですか？"},
          {StrId::Msg_ConfirmDeleteUnit,
           L"このバックアップユニットを削除してもよろしいですか？"},
          {StrId::Msg_ConfirmExit, L"SureBackupを終了してもよろしいですか？"},
          {StrId::Msg_ConfirmTitle, L"確認"},
          {StrId::Msg_SelectFirst,
           L"最初にバックアップセットまたはユニットを選択してください。"},
          {StrId::Msg_ProcessErrors,
           L"エラーが発生しました。ログを確認してください。"},
          {StrId::Msg_ProcessSuccess, L"バックアップが正常に完了しました。"},
          {StrId::Msg_StatusTitle, L"ステータス"},
          {StrId::Main_Processing,
           L"バックアップ処理中です。しばらくお待ちください..."}};
    } else if (isSpanish) {
      // Spanish (Español)
      s_strings = {
          {StrId::Menu_File, L"Archivo"},
          {StrId::Menu_NewSet, L"Nuevo Conjunto de Respaldo"},
          {StrId::Menu_Exit, L"Salir"},
          {StrId::Menu_Run, L"Ejecutar"},
          {StrId::Menu_RunSet, L"Ejecutar Conjunto de Respaldo"},
          {StrId::Menu_Preview, L"Vista Previa de Respaldo (Simulación)"},
          {StrId::Menu_Verify, L"Verificar Integridad"},
          {StrId::Menu_Help, L"Ayuda"},
          {StrId::Menu_About, L"Acerca de SureBackup"},
          {StrId::Menu_Set, L"Conjunto"},
          {StrId::Menu_Unit, L"Unidad"},
          {StrId::Menu_Backup, L"Respaldo"},
          {StrId::Menu_Log, L"Registro"},
          {StrId::Menu_LogHistory, L"Historial de Ejecución..."},

          {StrId::Ctx_Run, L"Ejecutar"},
          {StrId::Ctx_Preview, L"Vista Previa"},
          {StrId::Ctx_EditUnit, L"Editar unidad de respaldo"},
          {StrId::Ctx_EditSet, L"Editar conjunto de respaldo"},
          {StrId::Ctx_AddUnit, L"Añadir unidad"},
          {StrId::Ctx_Duplicate, L"Duplicar"},
          {StrId::Ctx_Delete, L"Eliminar"},
          {StrId::Ctx_Rename, L"Renombrar"},
          {StrId::Ctx_Refresh, L"Refrescar"},
          {StrId::Ctx_SetAsSource, L"Establecer como Origen"},
          {StrId::Ctx_SetAsTarget, L"Establecer como Destino"},

          {StrId::Dlg_UnitName, L"Nombre de la Unidad de Respaldo:"},
          {StrId::Dlg_Source, L"Ruta de la Carpeta de Origen:"},
          {StrId::Dlg_Target, L"Ruta de la Carpeta de Destino:"},
          {StrId::Dlg_Browse, L"..."},
          {StrId::Dlg_MapNetwork, L"Mapear Unidad de Red..."},
          {StrId::Dlg_Mode_Copy, L"Copia Incremental (Agregar)"},
          {StrId::Dlg_Mode_Sync, L"Sincronización (Espejo)"},
          {StrId::Dlg_Mode_Verify, L"Solo Verificar Integridad"},
          {StrId::Dlg_Mode_VerifyOnly, L"Solo Verificar Integridad"},
          {StrId::Dlg_Verification, L"Método de Verificación:"},
          {StrId::Dlg_Verify_Full, L"Byte por Byte (Completo)"},
          {StrId::Dlg_Verify_Criteria, L"Solo Tamaño y Fecha"},
          {StrId::Dlg_ErrorPolicy, L"Política de Manejo de Errores:"},
          {StrId::Dlg_Policy_Cont, L"Continuar (Omitir Archivo)"},
          {StrId::Dlg_Policy_Susp, L"Suspender Operaciones"},
          {StrId::Dlg_Engine, L"Motor de Procesamiento:"},
          {StrId::Dlg_Btn_Save, L"GUARDAR UNIDAD DE RESPALDO"},
          {StrId::Dlg_SetName, L"Nombre del Conjunto de Respaldo:"},
          {StrId::Dlg_Description, L"Descripción del Conjunto:"},
          {StrId::Dlg_UnitsInSet, L"Unidades en el Conjunto:"},
          {StrId::Dlg_Btn_Up, L"Mover ARRIBA"},
          {StrId::Dlg_Btn_Down, L"Mover ABAJO"},
          {StrId::Dlg_SchedFrq, L"Frecuencia de Programación:"},
          {StrId::Dlg_Sched_Manual, L"Ejecución Manual"},
          {StrId::Dlg_Sched_Daily, L"Tarea Diaria"},
          {StrId::Dlg_Sched_Weekly, L"Tarea Semanal"},
          {StrId::Dlg_Time_Title, L"Hora de Ejecución (HH:MM):"},
          {StrId::Dlg_Day_Title, L"Día Activo (Semanal):"},
          {StrId::Dlg_Btn_SaveSet, L"GUARDAR CONJUNTO DE RESPALDO"},

          {StrId::Main_Stop, L"DETENER TODAS LAS TAREAS"},
          {StrId::Main_MaxLog, L"MAXIMIZAR VISTA DE REGISTRO"},
          {StrId::Main_RestoreLayout, L"RESTAURAR DISEÑO"},
          {StrId::Main_SrcPath, L"Origen: "},
          {StrId::Main_DstPath, L"Destino: "},
          {StrId::Main_Error, L"Error"},
          {StrId::Main_Info, L"Información"},
          {StrId::Main_WorkerStop, L"PARAR"},
          {StrId::Main_Ready, L"Listo"},
          {StrId::Main_WorkerIdle, L"Trabajador Inactivo"},
          {StrId::Dlg_NewSet_Default, L"Nuevo Conjunto de Respaldo"},
          {StrId::Dlg_NewSet_Desc_Default, L"Colección de respaldos locales"},
          {StrId::Dlg_NewUnit_Default, L"Nueva Unidad de Respaldo"},

          {StrId::Eng_Std, L"Motor Estándar (Estable)"},
          {StrId::Eng_Par, L"Multihilo (Alta Velocidad)"},
          {StrId::Eng_Blk, L"Clon de Bloques (Sincronización Delta)"},
          {StrId::Eng_Vss, L"VSS (Copia instantánea)"},
          {StrId::Eng_Cmp, L"Motor de Comparación (Verificación)"},
          {StrId::Err_SamePath,
           L"Error: Las carpetas de origen y destino no pueden ser idénticas."},
          {StrId::Err_AlreadyRunning,
           L"Ya hay una copia de seguridad en curso."},
          {StrId::Err_PathOverlap,
           L"Error: Las carpetas de origen y destino no pueden superponerse."},
          {StrId::Ctx_SetAsSource, L"Establecer como origen"},
          {StrId::Ctx_SetAsTarget, L"Establecer como destino"},
          {StrId::Menu_Set, L"Conjunto"},
          {StrId::Ctx_AddSet, L"Añadir conjunto"},

          {StrId::Day_Sun, L"Domingo"},
          {StrId::Day_Mon, L"Lunes"},
          {StrId::Day_Tue, L"Martes"},
          {StrId::Day_Wed, L"Miércoles"},
          {StrId::Day_Thu, L"Jueves"},
          {StrId::Day_Fri, L"Viernes"},
          {StrId::Day_Sat, L"Sábado"},
          {StrId::Dlg_History_Title, L"Historial de Ejecución"},
          {StrId::Dlg_History_Date, L"Fecha y Hora"},
          {StrId::Dlg_History_Task, L"Nombre de la Tarea"},
          {StrId::Dlg_History_Open, L"Abrir Registro"},

          {StrId::Msg_ConfirmDeleteSet,
           L"¿Está seguro de que desea eliminar este conjunto de respaldo?"},
          {StrId::Msg_ConfirmDeleteUnit,
           L"¿Está seguro de que desea eliminar esta unidad de respaldo?"},
          {StrId::Msg_ConfirmExit,
           L"¿Está seguro de que desea salir de SureBackup?"},
          {StrId::Msg_ConfirmTitle, L"Confirmar"},
          {StrId::Msg_SelectFirst,
           L"Por favor, seleccione primero un conjunto o unidad de "
           L"respaldo."},
          {StrId::Msg_ProcessErrors,
           L"Respaldo procesado con errores. Verifique el registro."},
          {StrId::Msg_ProcessSuccess, L"Respaldo completado con éxito."},
          {StrId::Msg_StatusTitle, L"Estado"},
          {StrId::Main_Processing,
           L"Por favor espere, procesando respaldo..."}};
    } else if (isFrench) {
      // French (Français)
      s_strings = {
          {StrId::Menu_File, L"Fichier"},
          {StrId::Menu_NewSet, L"Nouvel Ensemble de Sauvegarde"},
          {StrId::Menu_Exit, L"Quitter"},
          {StrId::Menu_Run, L"Exécuter"},
          {StrId::Menu_RunSet, L"Exécuter l'Ensemble de Sauvegarde"},
          {StrId::Menu_Preview, L"Aperçu de Sauvegarde (Simulation)"},
          {StrId::Menu_Verify, L"Vérifier l'Intégrité"},
          {StrId::Menu_Help, L"Aide"},
          {StrId::Menu_About, L"À propos de SureBackup"},
          {StrId::Menu_Set, L"Ensemble"},
          {StrId::Menu_Unit, L"Unité"},
          {StrId::Menu_Backup, L"Sauvegarde"},
          {StrId::Menu_Log, L"Journal"},
          {StrId::Menu_LogHistory, L"Historique d'exécution..."},

          {StrId::Ctx_Run, L"Exécuter"},
          {StrId::Ctx_Preview, L"Aperçu"},
          {StrId::Ctx_EditUnit, L"Modifier l'unité de sauvegarde"},
          {StrId::Ctx_EditSet, L"Modifier l'ensemble de sauvegarde"},
          {StrId::Ctx_AddUnit, L"Ajouter une unité de sauvegarde"},
          {StrId::Ctx_Duplicate, L"Dupliquer"},
          {StrId::Ctx_Delete, L"Supprimer"},
          {StrId::Ctx_Rename, L"Renommer"},
          {StrId::Ctx_Refresh, L"Rafraîchir"},
          {StrId::Ctx_SetAsSource, L"Définir comme source"},
          {StrId::Ctx_SetAsTarget, L"Définir comme cible"},
          {StrId::Menu_Set, L"Ensemble"},
          {StrId::Ctx_AddSet, L"Ajouter un ensemble"},

          {StrId::Dlg_UnitName, L"Nom de l'Unité de Sauvegarde:"},
          {StrId::Dlg_Source, L"Chemin du Dossier Source:"},
          {StrId::Dlg_Target, L"Chemin du Dossier Cible:"},
          {StrId::Dlg_Browse, L"..."},
          {StrId::Dlg_MapNetwork, L"Mapper Lecteur Réseau..."},
          {StrId::Dlg_Mode_Copy, L"Copie Incrémentielle (Ajout)"},
          {StrId::Dlg_Mode_Sync, L"Synchronisation (Miroir)"},
          {StrId::Dlg_Mode_Verify, L"Vérifier l'Intégrité Uniquement"},
          {StrId::Dlg_Mode_VerifyOnly, L"Vérifier l'Intégrité Uniquement"},
          {StrId::Dlg_Verification, L"Méthode de Vérification:"},
          {StrId::Dlg_Verify_Full, L"Octet par Octet (Complet)"},
          {StrId::Dlg_Verify_Criteria, L"Taille et Date Uniquement"},
          {StrId::Dlg_ErrorPolicy, L"Politique de Gestion des Erreurs:"},
          {StrId::Dlg_Policy_Cont, L"Continuer (Ignorer le Fichier)"},
          {StrId::Dlg_Policy_Susp, L"Suspendre les Opérations"},
          {StrId::Dlg_Engine, L"Moteur de Traitement:"},
          {StrId::Dlg_Btn_Save, L"ENREGISTRER L'UNITÉ DE SAUVEGARDE"},
          {StrId::Dlg_SetName, L"Nom de l'Ensemble de Sauvegarde:"},
          {StrId::Dlg_Description, L"Description de l'Ensemble:"},
          {StrId::Dlg_UnitsInSet, L"Unités dans l'Ensemble:"},
          {StrId::Dlg_Btn_Up, L"Déplacer vers le HAUT"},
          {StrId::Dlg_Btn_Down, L"Déplacer vers le BAS"},
          {StrId::Dlg_SchedFrq, L"Fréquence de Planification:"},
          {StrId::Dlg_Sched_Manual, L"Exécution Manuelle"},
          {StrId::Dlg_Sched_Daily, L"Tâche Quotidienne"},
          {StrId::Dlg_Sched_Weekly, L"Tâche Hebdomadaire"},
          {StrId::Dlg_Time_Title, L"Heure d'Exécution (HH:MM):"},
          {StrId::Dlg_Day_Title, L"Jour Actif (Hebdomadaire):"},
          {StrId::Dlg_Btn_SaveSet, L"ENREGISTRER L'ENSEMBLE"},

          {StrId::Main_Stop, L"ARRÊTER TOUTES LES TÂCHES"},
          {StrId::Main_MaxLog, L"MAXIMISER LA VUE DU JOURNAL"},
          {StrId::Main_RestoreLayout, L"RESTAURER DISPOSITION"},
          {StrId::Main_SrcPath, L"Source: "},
          {StrId::Main_DstPath, L"Cible: "},
          {StrId::Main_Error, L"Erreur"},
          {StrId::Main_Info, L"Informations"},
          {StrId::Main_WorkerStop, L"ARRÊT"},
          {StrId::Main_Ready, L"Prêt"},
          {StrId::Main_WorkerIdle, L"Processus Inactif"},
          {StrId::Dlg_NewSet_Default, L"Nouvel Ensemble de Sauvegarde"},
          {StrId::Dlg_NewSet_Desc_Default, L"Collection de sauvegardes"},
          {StrId::Dlg_NewUnit_Default, L"Nouvelle Unité de Sauvegarde"},

          {StrId::Eng_Std, L"Moteur Standard (Stable)"},
          {StrId::Eng_Par, L"Multithread (Haute Vitesse)"},
          {StrId::Eng_Blk, L"Clone de Bloc (Synchro Delta)"},
          {StrId::Eng_Vss, L"VSS (Instantané)"},
          {StrId::Eng_Cmp, L"Moteur de Comparaison (Vérification)"},
          {StrId::Err_SamePath, L"Erreur: Les dossiers source et cible ne "
                                L"peuvent pas être identiques."},
          {StrId::Err_AlreadyRunning, L"Une sauvegarde est déjà en cours."},
          {StrId::Err_PathOverlap, L"Erreur: Les dossiers source et cible ne "
                                   L"peuvent pas se chevaucher."},

          {StrId::Day_Sun, L"Dimanche"},
          {StrId::Day_Mon, L"Lundi"},
          {StrId::Day_Tue, L"Mardi"},
          {StrId::Day_Wed, L"Mercredi"},
          {StrId::Day_Thu, L"Jeudi"},
          {StrId::Day_Fri, L"Vendredi"},
          {StrId::Day_Sat, L"Samedi"},
          {StrId::Dlg_History_Title, L"Historique d'exécution"},
          {StrId::Dlg_History_Date, L"Date et Heure"},
          {StrId::Dlg_History_Task, L"Nom de la tâche"},
          {StrId::Dlg_History_Open, L"Ouvrir le journal"},

          {StrId::Msg_ConfirmDeleteSet, L"Êtes-vous sûr de vouloir supprimer "
                                        L"cet ensemble de sauvegarde ?"},
          {StrId::Msg_ConfirmDeleteUnit, L"Êtes-vous sûr de vouloir supprimer "
                                         L"cette unité de sauvegarde ?"},
          {StrId::Msg_ConfirmExit,
           L"Êtes-vous sûr de vouloir quitter SureBackup ?"},
          {StrId::Msg_ConfirmTitle, L"Confirmer"},
          {StrId::Msg_SelectFirst, L"Veuillez d'abord sélectionner un ensemble "
                                   L"ou une unité de sauvegarde."},
          {StrId::Msg_ProcessErrors, L"Sauvegarde traitée avec des erreurs. "
                                     L"Vérifiez le journal."},
          {StrId::Msg_ProcessSuccess, L"Sauvegarde terminée avec succès."},
          {StrId::Msg_StatusTitle, L"Statut"},
          {StrId::Main_Processing,
           L"Veuillez patienter, traitement de la sauvegarde..."}};
    } else if (isGerman) {
      // German (Deutsch)
      s_strings = {
          {StrId::Menu_File, L"Datei"},
          {StrId::Menu_NewSet, L"Neues Backup-Set"},
          {StrId::Menu_Exit, L"Beenden"},
          {StrId::Menu_Run, L"Ausführen"},
          {StrId::Menu_RunSet, L"Backup-Set Ausführen"},
          {StrId::Menu_Preview, L"Backup-Vorschau (Simulation)"},
          {StrId::Menu_Verify, L"Integrität Prüfen"},
          {StrId::Menu_Help, L"Hilfe"},
          {StrId::Menu_About, L"Über SureBackup"},
          {StrId::Menu_Set, L"Set"},
          {StrId::Menu_Unit, L"Einheit"},
          {StrId::Menu_Backup, L"Backup"},
          {StrId::Menu_Log, L"Protokoll"},
          {StrId::Menu_LogHistory, L"Ausführungsverlauf..."},

          {StrId::Ctx_Run, L"Ausführen"},
          {StrId::Ctx_Preview, L"Vorschau"},
          {StrId::Ctx_EditUnit, L"Backup-Einheit bearbeiten"},
          {StrId::Ctx_EditSet, L"Backup-Set bearbeiten"},
          {StrId::Ctx_AddUnit, L"Einheit hinzufügen"},
          {StrId::Ctx_Duplicate, L"Duplizieren"},
          {StrId::Ctx_Delete, L"Löschen"},
          {StrId::Ctx_Rename, L"Umbenennen"},
          {StrId::Ctx_Refresh, L"Aktualisieren"},
          {StrId::Ctx_SetAsSource, L"Als Quelle Festlegen"},
          {StrId::Ctx_SetAsTarget, L"Als Ziel Festlegen"},
          {StrId::Menu_Set, L"Set"},
          {StrId::Ctx_AddSet, L"Set hinzufügen"},

          {StrId::Dlg_UnitName, L"Name der Backup-Einheit:"},
          {StrId::Dlg_Source, L"Quellordner-Pfad:"},
          {StrId::Dlg_Target, L"Zielordner-Pfad:"},
          {StrId::Dlg_Browse, L"..."},
          {StrId::Dlg_MapNetwork, L"Netzlaufwerk Verbinden..."},
          {StrId::Dlg_Mode_Copy, L"Inkrementelle Kopie (Hinzufügen)"},
          {StrId::Dlg_Mode_Sync, L"Synchronisation (Spiegel)"},
          {StrId::Dlg_Mode_Verify, L"Nur Integrität Überprüfen"},
          {StrId::Dlg_Mode_VerifyOnly, L"Nur Integrität Überprüfen"},
          {StrId::Dlg_Verification, L"Überprüfungsmethode:"},
          {StrId::Dlg_Verify_Full, L"Byte für Byte (Vollständig)"},
          {StrId::Dlg_Verify_Criteria, L"Nur Größe und Zeitstempel"},
          {StrId::Dlg_ErrorPolicy, L"Fehlerbehandlungs-Richtlinie:"},
          {StrId::Dlg_Policy_Cont, L"Fortsetzen (Datei Überspringen)"},
          {StrId::Dlg_Policy_Susp, L"Operationen Aussetzen"},
          {StrId::Dlg_Engine, L"Verarbeitungs-Engine:"},
          {StrId::Dlg_Btn_Save, L"BACKUP-EINHEIT SPEICHERN"},
          {StrId::Dlg_SetName, L"Name des Backup-Sets:"},
          {StrId::Dlg_Description, L"Beschreibung des Sets:"},
          {StrId::Dlg_UnitsInSet, L"Einheiten im Set:"},
          {StrId::Dlg_Btn_Up, L"Nach OBEN verschieben"},
          {StrId::Dlg_Btn_Down, L"Nach UNTEN verschieben"},
          {StrId::Dlg_SchedFrq, L"Zeitplan-Frequenz:"},
          {StrId::Dlg_Sched_Manual, L"Manuelle Ausführung"},
          {StrId::Dlg_Sched_Daily, L"Tägliche Aufgabe"},
          {StrId::Dlg_Sched_Weekly, L"Wöchentliche Aufgabe"},
          {StrId::Dlg_Time_Title, L"Ausführungszeit (HH:MM):"},
          {StrId::Dlg_Day_Title, L"Aktiver Tag (Wöchentlich):"},
          {StrId::Dlg_Btn_SaveSet, L"BACKUP-SET SPEICHERN"},

          {StrId::Main_Stop, L"ALLE AUFGABEN STOPPEN"},
          {StrId::Main_MaxLog, L"PROTOKOLL-ANSICHT MAXIMIEREN"},
          {StrId::Main_RestoreLayout, L"LAYOUT WIEDERHERSTELLEN"},
          {StrId::Main_SrcPath, L"Quelle: "},
          {StrId::Main_DstPath, L"Ziel: "},
          {StrId::Main_Error, L"Fehler"},
          {StrId::Main_Info, L"Information"},
          {StrId::Main_WorkerStop, L"STOPP"},
          {StrId::Main_Ready, L"Bereit"},
          {StrId::Main_WorkerIdle, L"Thread im Leerlauf"},
          {StrId::Dlg_NewSet_Default, L"Neues Backup-Set"},
          {StrId::Dlg_NewSet_Desc_Default, L"Lokale Backup-Sammlung"},
          {StrId::Dlg_NewUnit_Default, L"Neue Backup-Einheit"},

          {StrId::Eng_Std, L"Standard-Engine (Stabil)"},
          {StrId::Eng_Par, L"Multithread (Hohe Geschwindigkeit)"},
          {StrId::Eng_Blk, L"Block-Klon (Delta-Synchro)"},
          {StrId::Eng_Vss, L"VSS (Snapshot-Kopie)"},
          {StrId::Eng_Cmp, L"Vergleichs-Engine (Prüfung)"},
          {StrId::Err_SamePath,
           L"Fehler: Quell- und Zielpfad dürfen nicht identisch sein."},
          {StrId::Err_AlreadyRunning, L"Sicherung läuft bereits."},
          {StrId::Err_PathOverlap,
           L"Fehler: Quell- und Zielpfad dürfen sich nicht überschneiden."},

          {StrId::Day_Sun, L"Sonntag"},
          {StrId::Day_Mon, L"Montag"},
          {StrId::Day_Tue, L"Dienstag"},
          {StrId::Day_Wed, L"Mittwoch"},
          {StrId::Day_Thu, L"Donnerstag"},
          {StrId::Day_Fri, L"Freitag"},
          {StrId::Day_Sat, L"Samstag"},
          {StrId::Dlg_History_Title, L"Ausführungsverlauf"},
          {StrId::Dlg_History_Date, L"Datum und Uhrzeit"},
          {StrId::Dlg_History_Task, L"Task-Name"},
          {StrId::Dlg_History_Open, L"Protokoll öffnen"},

          {StrId::Msg_ConfirmDeleteSet,
           L"Sind Sie sicher, dass Sie dieses Backup-Set löschen möchten?"},
          {StrId::Msg_ConfirmDeleteUnit,
           L"Sind Sie sicher, dass Sie diese Backup-Einheit löschen möchten?"},
          {StrId::Msg_ConfirmExit,
           L"Sind Sie sicher, dass Sie SureBackup beenden möchten?"},
          {StrId::Msg_ConfirmTitle, L"Bestätigen"},
          {StrId::Msg_SelectFirst,
           L"Bitte wählen Sie zuerst ein Backup-Set oder eine Einheit aus."},
          {StrId::Msg_ProcessErrors,
           L"Backup mit Fehlern verarbeitet. Protokoll prüfen."},
          {StrId::Msg_ProcessSuccess, L"Backup erfolgreich abgeschlossen."},
          {StrId::Msg_StatusTitle, L"Status"},
          {StrId::Main_Processing,
           L"Bitte warten, Backup wird verarbeitet..."}};
    } else {
      // English (Default)
      s_strings = {
          {StrId::Menu_File, L"File"},
          {StrId::Menu_NewSet, L"New Backup Set"},
          {StrId::Menu_Exit, L"Exit"},
          {StrId::Menu_Run, L"Run"},
          {StrId::Menu_RunSet, L"Run Backup Set"},
          {StrId::Menu_Preview, L"Backup Preview (Dry Run)"},
          {StrId::Menu_Verify, L"Verify (Check Integrity)"},
          {StrId::Menu_Help, L"Help"},
          {StrId::Menu_About, L"About SureBackup"},
          {StrId::Menu_Set, L"Set"},
          {StrId::Menu_Unit, L"Unit"},
          {StrId::Menu_Backup, L"Backup"},
          {StrId::Menu_Log, L"Log"},
          {StrId::Menu_LogHistory, L"Execution History..."},

          {StrId::Ctx_Run, L"Run"},
          {StrId::Ctx_Preview, L"Preview"},
          {StrId::Ctx_EditUnit, L"Edit Backup Unit"},
          {StrId::Ctx_EditSet, L"Edit Backup Set"},
          {StrId::Ctx_AddUnit, L"Add Backup Unit"},
          {StrId::Ctx_Duplicate, L"Duplicate"},
          {StrId::Ctx_Delete, L"Delete"},
          {StrId::Ctx_Rename, L"Rename"},
          {StrId::Ctx_Refresh, L"Refresh"},
          {StrId::Ctx_SetAsSource, L"Set as Source"},
          {StrId::Ctx_SetAsTarget, L"Set as Target"},
          {StrId::Menu_Set, L"Set"},
          {StrId::Ctx_AddSet, L"Add Set"},

          {StrId::Msg_ConfirmDeleteSet,
           L"Are you sure you want to delete this backup set?"},
          {StrId::Msg_ConfirmDeleteUnit,
           L"Are you sure you want to delete this backup unit?"},
          {StrId::Msg_ConfirmExit,
           L"Are you sure you want to exit SureBackup?"},
          {StrId::Msg_ConfirmTitle, L"Confirm Delete"},
          {StrId::Msg_SelectFirst,
           L"Please select a backup set or unit first."},
          {StrId::Msg_ProcessErrors,
           L"Backup processed with errors. Check log."},
          {StrId::Msg_ProcessSuccess, L"Backup completed successfully."},
          {StrId::Msg_StatusTitle, L"Status"},
          {StrId::Main_Processing, L"Please wait, processing backup..."},

          {StrId::Dlg_UnitName, L"Backup Unit Name:"},
          {StrId::Dlg_Source, L"Source Folder Path:"},
          {StrId::Dlg_Target, L"Target Folder Path:"},
          {StrId::Dlg_Browse, L"..."},
          {StrId::Dlg_MapNetwork, L"Map Network Drive..."},
          {StrId::Dlg_Mode_Copy, L"Incremental Copy (Append)"},
          {StrId::Dlg_Mode_Sync, L"Synchronization (Mirror)"},
          {StrId::Dlg_Mode_Verify, L"Integrity Verify Only"},
          {StrId::Dlg_Mode_VerifyOnly, L"Integrity Verify Only"},
          {StrId::Dlg_Verification, L"Verification Method:"},
          {StrId::Dlg_Verify_Full, L"Byte-by-Byte (Complete)"},
          {StrId::Dlg_Verify_Criteria, L"File Size & Timestamp Only"},
          {StrId::Dlg_ErrorPolicy, L"Error Handling Policy:"},
          {StrId::Dlg_Policy_Cont, L"Continue (Skip File)"},
          {StrId::Dlg_Policy_Susp, L"Suspend Operations"},
          {StrId::Dlg_Engine, L"Processing Engine:"},
          {StrId::Dlg_Btn_Save, L"SAVE BACKUP UNIT"},
          {StrId::Dlg_SetName, L"Backup Set Name:"},
          {StrId::Dlg_Description, L"Set Description:"},
          {StrId::Dlg_UnitsInSet, L"Units in Backup Set:"},
          {StrId::Dlg_Btn_Up, L"Move UP"},
          {StrId::Dlg_Btn_Down, L"Move DOWN"},
          {StrId::Dlg_SchedFrq, L"Schedule Frequency:"},
          {StrId::Dlg_Sched_Manual, L"Manual Execution"},
          {StrId::Dlg_Sched_Daily, L"Daily Task"},
          {StrId::Dlg_Sched_Weekly, L"Weekly Task"},
          {StrId::Dlg_Time_Title, L"Execution Time (HH:MM):"},
          {StrId::Dlg_Day_Title, L"Active Day (Weekly):"},
          {StrId::Dlg_Btn_SaveSet, L"SAVE BACKUP SET"},

          {StrId::Main_Stop, L"STOP ALL TASKS"},
          {StrId::Main_MaxLog, L"MAXIMIZE LOG VIEW"},
          {StrId::Main_RestoreLayout, L"RESTORE LAYOUT"},
          {StrId::Main_SrcPath, L"Source: "},
          {StrId::Main_DstPath, L"Target: "},
          {StrId::Main_Error, L"Error"},
          {StrId::Main_Info, L"Information"},
          {StrId::Main_WorkerStop, L"STOP"},
          {StrId::Main_Ready, L"Ready"},
          {StrId::Main_WorkerIdle, L"Worker Idle"},
          {StrId::Dlg_NewSet_Default, L"New Backup Set"},
          {StrId::Dlg_NewSet_Desc_Default, L"Local backup collection"},
          {StrId::Dlg_NewUnit_Default, L"New Backup Unit"},

          {StrId::Eng_Std, L"Standard Engine (Stable)"},
          {StrId::Eng_Par, L"Multithreaded (High Speed)"},
          {StrId::Eng_Blk, L"Block Clone (Delta Sync)"},
          {StrId::Eng_Vss, L"VSS (Snapshot Copy)"},
          {StrId::Eng_Cmp, L"Comparison Engine (Verify)"},
          {StrId::Err_SamePath,
           L"Error: Source and target folders cannot be identical."},
          {StrId::Err_AlreadyRunning, L"A backup is already running."},
          {StrId::Err_PathOverlap,
           L"Error: Source and target folders cannot overlap."},

          {StrId::Day_Sun, L"Sunday"},
          {StrId::Day_Mon, L"Monday"},
          {StrId::Day_Tue, L"Tuesday"},
          {StrId::Day_Wed, L"Wednesday"},
          {StrId::Day_Thu, L"Thursday"},
          {StrId::Day_Fri, L"Friday"},
          {StrId::Day_Sat, L"Saturday"},
          {StrId::Dlg_History_Title, L"Execution History"},
          {StrId::Dlg_History_Date, L"Date & Time"},
          {StrId::Dlg_History_Task, L"Task Name"},
          {StrId::Dlg_History_Open, L"Open Log"}};
    }
  }

  static const wchar_t *Get(StrId id) {
    auto it = s_strings.find(id);
    if (it != s_strings.end())
      return it->second.c_str();
    return L"?";
  }
};

inline std::map<StrId, std::wstring> Localization::s_strings;
